### PR TITLE
Task/create spm

### PR DESCRIPTION
**Pull request by anthonyGuiguen**
Create Swift Package Manager with CometD sources

### CODE REVIEW

**Review by StevenWatremez — COMMENTED** [review]
Good, it's nice to see this separate CometdClient :D 

For this project you need to add a `.gitignore` in addition.

**Comment by anthonyGuiguen** [comment]
@StevenWatremez Yes 😁
We already have a `.gitignore` : https://github.com/Insurlytech/CometDClient-iOS/blob/master/.gitignore

**Comment by StevenWatremez** [comment]
Ok np. I didn't see this because it was not inside your first PR. You copy this from accio :D https://github.com/Insurlytech/CometDClient-iOS/blob/edff4d4bca3ae75bbde52e549b3bde999f66ce42/.gitignore#L71

rearrange to match with this repo and it will be good

**Comment by anthonyGuiguen** [comment]
@StevenWatremez It's not for our Accio project ^^.
It's a `.gitignore` generated by Github. And `.accio/`it's for this case https://github.com/github/gitignore/pull/3046

**Comment by StevenWatremez** [comment]
Nice it's good to know 👍

**Review by StevenWatremez — APPROVED** [review]

**Pull request merged**
